### ISSUE TITLE
Update examples to use task execution engine

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#103]
Some examples need to updated to use the task execution engine

## Definition of Done
- [x] The identified examples illustrate the use of the task execution engine

Examples to update:
- [x] tensorflow-mnist-pixel-threshold
- [x] tensorflow-mnist-classifier
- [x] tensorflow-mnist-model-inversion

**Comment by jkglasbrenner** [comment]
Closed by #270
