### ISSUE TITLE
Create a UI Mockup for Queue entities within Dioptra

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#106]
Create a user interface for the management and viewing of Queues

## Definition of Done
- [x] A draft mock-up of the Queue UI is completed
- [x] A group meeting to review draft mock-up and provide feedback
- [x] A finalized mock-up which accounts for all received feedback

Relevant REST APIs:
- Queue
	- Displays
		- [ ] GET /api/queue/ Gets a list of all registered queues
		- [ ] GET /api/queue/{queueId} Gets a queue by its unique identifier
		- [ ] GET /api/queue/name/{queueName} Gets a queue by its unique name
	- Utilities
		- [ ] POST /api/queue/ Creates a new queue via a queue registration form
		- [ ] DELETE /api/queue/{queueId} Deletes a queue by its unique identifier
		- [ ] PUT /api/queue/{queueId} Modifies a queue by its unique identifier
		- [ ] DELETE /api/queue/{queueId}/lock Removes the lock from the queue (id reference) if it exists
		- [ ] PUT /api/queue/{queueId}/lock Locks the queue (id reference) if it is unlocked
		- [ ] DELETE /api/queue/name/{queueName} Deletes a queue by its unique name
		- [ ] PUT /api/queue/name/{queueName} Modifies a queue by its unique name
		- [ ] DELETE /api/queue/name/{queueName}/lock Removes the lock from the queue (name reference) if it exists
		- [ ] PUT /api/queue/name/{queueName}/lock Locks the queue (name reference) if it is unlocked

**Comment by hbooth** [comment]
see #15

**Comment by pauldavidrowe** [comment]
Discussed and agreed to at 4/11 meeting.
