### ISSUE TITLE
Create a UI Mockup for User Management Functionality

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#107]
Create a mockup of the user interface for managing users, accounts, and privileges for access control.

## Definition of done
- [x] A draft mock-up of the User Management UI is completed
- [x] A group meeting to review draft mock-up and provide feedback
- [x] A finalized mock-up which accounts for all received feedback

Relevant REST APIs:
- User Management (Admin)
	- Displays
		- [ ] GET api/.../ Get all users
		- [ ] GET api/.../{userName} Get user by their unique name
		- [ ] GET api/.../{privilege} Get all users for a certain privilege level
	- Utilities
		- [ ] POST api/.../{userName} Creates a user with the given name
		- [ ] PUT api/.../{userName} Modifies the user with the given name
		- [ ] DELETE api/.../{userName} Deletes the user with the given name

**Comment by jkglasbrenner** [comment]
Reviewed and accepted at development team meeting on July 18, 2023
