### ISSUE TITLE
Provide ability to associate metadata information with task plug-ins

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#112]
Several use cases would be supported by the ability to associate metadata with a task plug-in

The metadata would include/enable things like:
- name (currently it's fixed and not editable)
- inputs and output and their types
- user-defined tags (to enable grouping of plugins)

Along with providing REST API endpoints allowing this functionality, the user interface elements will need to be added as well

**Comment by jkglasbrenner** [comment]
To be broken down into smaller issues.

**Comment by jkglasbrenner** [comment]
Superseded by #241 and #184
