### ISSUE TITLE
Unit Testing - Task Plugins - Random

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#120]
Develop unit tests for the following functions.

**Random:**
- [x] [`init_rng` in dioptra_builtins/random/rng.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/random/rng.py)
- [x] [`draw_random_integer` in dioptra_builtins/random/sample.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/random/sample.py)
- [x] [`draw_random_integers` in dioptra_builtins/random/sample.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/random/sample.py)

**Comment by lbarbMITRE** [comment]
Closed by #162
