### ISSUE TITLE
Unit Tests - Task Plugins - Metrics

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#121]
Develop unit tests for the following functions.

**Metrics:**
- [x] [`get_distance_metric_list` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`get_distance_metric` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`l_inf_norm` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`l_1_norm` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`l_2_norm` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`paired_cosine_similarities` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`paired_euclidean_distances` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`paired_manhattan_distances` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`paired_wasserstein_distances` in dioptra_builtins/metrics/distance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/distance.py)
- [x] [`get_performance_metric_list` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`get_performance_metric` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`accuracy` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`roc_auc` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`categorical_accuracy` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`mcc` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`f1` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`precision` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)
- [x] [`recall` in dioptra_builtins/metrics/performance.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/metrics/performance.py)

**Comment by jkglasbrenner** [comment]
Closed by #157
