### ISSUE TITLE
Unit Testing - Task Plugins - Artifacts

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#122]
Develop unit tests for the following functions.

**Artifacts:**
- [x] [`download_all_artifacts_in_run` in dioptra_builtins/artifacts/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/mlflow.py)
- [x] [`upload_data_frame_artifact` in dioptra_builtins/artifacts/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/mlflow.py)
- [x] [`upload_directory_as_tarball_artifact` in dioptra_builtins/artifacts/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/mlflow.py)
- [x] [`upload_file_as_artifact` in dioptra_builtins/artifacts/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/mlflow.py)
- [x] [`extract_tarfile` in dioptra_builtins/artifacts/utils.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/utils.py)
- [x] [`make_directories` in dioptra_builtins/artifacts/utils.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/artifacts/utils.py)

**Comment by pauldavidrowe** [comment]
Closed by pull request #169
