### ISSUE TITLE
Unit Testing - Task Plugin - Attacks

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#123]
Develop unit tests for the following functions.

**Attacks:**
- [ ] [`create_adversarial_fgm_dataset` in dioptra_builtins/attacks/fgm.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/attacks/fgm.py)

**Comment by keithmanville** [comment]
Won't fix
