### ISSUE TITLE
Unit Testing - Task Plugins - Data

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#124]
Develop unit tests for the following plugins.

**Data:**
- [ ] [`create_image_dataset` in dioptra_builtins/data/tensorflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/data/tensorflow.py)
- [ ] [`get_n_classes_from_directory_iterator` in dioptra_builtins/data/tensorflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/data/tensorflow.py)

**Comment by keithmanville** [comment]
Won't fix
