### ISSUE TITLE
Unit Testing - Task Plugins - Estimators

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#125]
Develop unit tests for the following functions.

**Estimators:**
- [ ] [`init_classifier` in dioptra_builtins/estimators/keras_classifiers.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/estimators/keras_classifiers.py)
- [ ] [`fit` in dioptra_builtins/estimators/methods.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/estimators/methods.py)
- [ ] [`predict` in dioptra_builtins/estimators/methods.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/estimators/methods.py)

**Comment by keithmanville** [comment]
Won't fix
