### ISSUE TITLE
Remove the Miniconda dependency from the Dioptra container images

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#135]
## Description 

The current container images provide a Python environment through Miniconda. Using Miniconda creates the following issues:

- **Slow build mechanisms:** The use of Miniconda introduces bottlenecks in the Dioptra build toolchain in two ways:
    - Updating the environment lockfiles requires rebuilding the entire image.
    - The hybrid approach to installing packages from both the conda repository and pip is slow, even when versions are pinned.
- **Difficult to support ARM64:** Miniconda does not have a universal installer for all ARM64 chipsets.
- **Larger images:** The Miniconda dependency tends to inflate the size of images by 1–3GB.
- **Licensing:** The [Anaconda Terms of Service](https://legal.anaconda.com/policies/en/#terms-of-service) changed in 2020. The free version of Anaconda/Miniconda is only available for Non-Commercial Personal, Educational, Open Source, and Small Business Use, making it difficult for large commercial organizations to use Dioptra.

The above issues can be resolved by switching to using system Python and pip in all of the container images.

## Definition of Done

- [x] Use of Miniconda is completely removed from the Dockerfiles and replaced with system Python, pip, and the Python standard library's `venv` module.
- [x] The container shell scripts are refactored to use Python's native virtual environments instead of conda environments.
- [x] The conda `environment.yml` files are replaced with `requirements.txt` lockfiles generated using [pip-compile](https://pip-tools.readthedocs.io/en/latest/).
- [x] The build scripts and configuration files are updated to handle the removal of the Miniconda dependency.
- [x] The example `tensorflow-mnist-classifier` is run end-to-end to ensure that the removal of Miniconda did not introduce any behavioral changes in the Dioptra containers.

**Comment by burakmuslu** [comment]
Upon updating packages within conda in line 230 of Dockerfile.mlflow-tracking, CLI presents Illegal instruction (core dumped) output..

Within ARM64, Conda requires libcrypto.so.1.1 and libssl.so.1.1 to function. Working solution to copy /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 /opt/conda/lib/libcrypto.so.1.1 and /usr/lib/aarch64-linux-gnu/libssl.so.1.1 /opt/conda/lib/libssl.so.1. This is

**Comment by burakmuslu** [comment]
Upon updating packages within conda in line 230 of Dockerfile.mlflow-tracking, CLI presents Illegal instruction (core dumped) output..

<img width="594" alt="Output 1" src="https://user-images.githubusercontent.com/123125488/228936743-319b229d-ab62-4d15-8db5-a4f734f554de.PNG">

Open issue: https://github.com/conda/conda/issues/10723
Issue with similar behavior / solution: https://github.com/conda/conda/issues/11795

Within ARM64, Conda requires libcrypto.so.1.1 and libssl.so.1.1 to function. Working solution to copy /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 /opt/conda/lib/libcrypto.so.1.1 and /usr/lib/aarch64-linux-gnu/libssl.so.1.1 /opt/conda/lib/libssl.so.1. It is not ideal to copy files over, and instead install the necessary packages or use symbolic links.

**Comment by jkglasbrenner** [comment]
Closed by #216
