### ISSUE TITLE
As a developer I need to be able to add my own custom containers in order to leverage other libraries

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#141]
**Definition of Done**
- [ ] Documentation is written that explains how to create a custom Docker file
- [ ] Documentation on how to include a pre-built custom container in the deployment

**Comment by hbooth** [comment]
Two scenarios:
 - have a base image and customize
 - have an existing image and what is needed to turn it into a worker container

**Comment by keithmanville** [comment]
Superseded by #295
