### ISSUE TITLE
Write MLFlow logging integration tests

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#144]
**Definition of Done**
- [ ] [`log_metrics` in dioptra_builtins/tracking/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/tracking/mlflow.py)
- [ ] [`log_parameters` in dioptra_builtins/tracking/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/tracking/mlflow.py)
- [ ] [`log_tensorflow_keras_estimator` in dioptra_builtins/tracking/mlflow.py](https://github.com/usnistgov/dioptra/blob/main/task-plugins/dioptra_builtins/tracking/mlflow.py)

**Comment by keithmanville** [comment]
OBE
