### ISSUE TITLE
Update the project's top-level README to point at new deployment method

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#153]
## Describe the documentation issue

The top-level project README is terse and does not direct new users to relevant information. The one section that it does contain about how to build the documentation references obsolete make commands.

At a minimum, it should be updated with a list of prerequisites, a quickstart for setting up and running Dioptra, and link users to relevant parts of the documentation.

Related: #142 

## Section of Documentation

[Top-level project README](https://github.com/usnistgov/dioptra/blob/main/README.md)

**Comment by hbooth** [comment]
Also Related #82

**Comment by pauldavidrowe** [comment]
This was addressed by resolving #87
