### ISSUE TITLE
Implement UI for Experiments and Jobs

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#161]
The wireframe mockups for Experiments and Jobs are now ready to be implemented.

Dependent on REST APIs being completed #214 

**Definition of Done**
- [ ] Initial UI is implemented for interacting with Experiments
- [ ] Initial UI is implemented for interacting with Jobs
- [ ] Team has tested and discussed UI implementation
- [ ] Code is merged into dev branch

**Comment by keithmanville** [comment]
closed by #521
