### ISSUE TITLE
Small Typo in Getting Started Docs/"Building the containers"

### ISSUE THREAD

**Issue by alexb1200** [usnistgov/dioptra#165]
**Description**
In the Getting Started Docs under the "Building the containers" subsection, the instruction to build the docker images fails due to a typo. 
The last target for make is "build-tensorflow2-cpu" which does not exist. It should be "build-tensorflow-cpu" which builds the container "tensorflow2-cpu". 

**Definition of Done**
- [ ] Fixed typo and merged into Dev

**Comment by jkglasbrenner** [comment]
Closed by #166
