### ISSUE TITLE
Implement UI for interacting with task plugins

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#184]
Implement the task plugin UI based on the wireframe mockups to use the expanded task plugin endpoints completed in #241 to show the metadata associated with the plugins.

**Definition of Done**

- [ ] Initial UI is implemented for interacting with task plugins
- [ ] Review of UI implementation by team
- [ ] Unit tests for the new UI functionality are implemented and passing
- [ ] Code is merged into dev

**Comment by keithmanville** [comment]
closed by #521
