### ISSUE TITLE
Create UI Mockup for Parameter Types

### ISSUE THREAD

**Issue by pauldavidrowe** [usnistgov/dioptra#194]
We need a way to create and interact with parameters types which are the input/output types of task plugins. Metadata:
- Name
- Description (optional)

**Definition of Done**
- [x] Draft mockup of task plugin types is implemented
- [x] Group meeting is held to review draft mockup
- [x] Finalized mockup accounting for all feedback

**Comment by lbarbMITRE** [comment]
See UI channel and teams for finished mockup.
