### ISSUE TITLE
Add restapi endpoints to support entity validation

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#209]
In order to support entity validation new REST API endpoints are required.
An initial mockup/proposal of what is needed is available on the entity-validation branch, within the unit-test src.
Taking this mockup as a starting new functionality is needed.

# Definition of Done
- [ ] Create a design proposal for new endpoints and present to team
- [ ] Implement Design proposal
- [ ] Update Dev Branch

**Comment by keithmanville** [comment]
stale
