### ISSUE TITLE
Formalize the existing Dioptra Client

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#210]
The current dioptra client class is in the examples folder and needs to be a first-class citizen of the Dioptra API. Moving the existing code into a top-level source folder is needed.

# Definition of Done
- [x] Move client to dioptra.client namespace
- [x] Insure the existing class is fully-documented
- [x] Merged into Dev branch

**Comment by jkglasbrenner** [comment]
Closed by #220
