### ISSUE TITLE
Implement REST API to support Experiments and Jobs UI

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#214]
The wireframe mockups for Experiments and Jobs is now ready to be implemented, but REST API support is needed.

# Definition of Done
- [x]  Tag Resource implemented
- [x] EntryPoint Resource implemented (including supporting resources like versions of EntryPoints, Parameters, and Parameter Values)
- [x] Group Resource implemented
- [x] Experiments updated to now include EntryPoints and Groups
- [ ] Jobs updated to use Parameter Values
- [ ] Unit Tests implemented
- [ ] passes static code analyzers
- [ ] Merged into Dev branch

**Comment by keithmanville** [comment]
closed by #521
