### ISSUE TITLE
Integrate Flask Login library

### ISSUE THREAD

**Issue by hbooth** [usnistgov/dioptra#221]
There is already an existing endpoint for creating a user account which can be found at: 
https://github.com/usnistgov/dioptra/blob/main/src/dioptra/restapi/shared/password/service.py
https://github.com/usnistgov/dioptra/blob/main/src/dioptra/restapi/user/service.py

Need to integrate with Flask Login with a login page to add the concept of a current user:
https://flask-login.readthedocs.io/en/latest/

Leverage [Flask-Login's "Remember Me" cookies](https://flask-login.readthedocs.io/en/latest/#cookie-settings) to add session expiration.

Do NOT merge this into "dev" branch. Merge into "auth" branch for initial implementation. 

# Definition of Done
- [x] Flask Login added as a dependency
- [x] Login endpoint added
- [x] Every endpoint requires a current user to access
- [x] Unit tests added for login
- [x] Merged into "auth" branch

**Comment by jkglasbrenner** [comment]
Closed by #305
