### ISSUE TITLE
Remove stale and unused branches from the repository

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#240]
There are multiple branches in the repo that contain code that is either defunct or was an earlier prototype that has since been merged. The goal is to remove all of the branches that no longer need to be kept around.

## Definition of Done

- [ ] All stale and unnecessary branches have been identified and removed from the repo.

**Comment by jtsextonMITRE** [comment]
My extra branches are deleted.

**Comment by jkglasbrenner** [comment]
I have also removed all of my extra branches

**Comment by alexb1200** [comment]
Removed my extra branch.
