### ISSUE TITLE
Restapi task plugin service creates platform-specific S3 key prefixes

### ISSUE THREAD

**Issue by chisholm** [usnistgov/dioptra#248]
**Describe the bug**
In restapi: the task plugin service creates a S3 key prefix using the Python `pathlib` module, which causes the key prefix syntax to be platform dependent: on Windows backslashes are used; on Linux/Mac, forward slashes are used.  This causes restapi unit tests to fail on Windows.

https://github.com/usnistgov/dioptra/blob/f6d1d94a0013ab117ea1ab1f51f0d467b262a911/src/dioptra/restapi/task_plugin/service.py#L108

**To Reproduce**

Run the restapi unit tests on Windows.

**Expected behavior**
Restapi unit tests pass.

**Desktop (please complete the following information):**
 - OS: Windows 10

Changing the above code to:

```python
prefix: Path = collection + "/" + task_plugin_name
```

enables the tests to pass.

**Comment by jkglasbrenner** [comment]
Closed by #255
