### ISSUE TITLE
[BUG] Deleting and re-registering an experiment fails

### ISSUE THREAD

**Issue by alexb1200** [usnistgov/dioptra#251]
**Describe the bug**
Deleting and re-registering an experiment fails with response "{'message': 'Bad Request - The experiment name on the registration form already exists on the MLFlow Tracking backend. Please select another and resubmit.'}"

**To Reproduce**
1. Send a delete request to the api for an experiment, for example "1"
2.  Try to register an experiment with the deleted experiment's name i.e. "mnist" 
3. See error

**Expected behavior**
Deleting and re-registering an experiment should show in the mlflow ui. 

This may be related https://github.com/mlflow/mlflow/issues/2651

**Comment by alexb1200** [comment]
Based on Discussions from our internal meeting, this may be desired behavior. The default behavior for mlflow is to flag experiments as deleted, and to disallow reuse of experiment names. In order to permanently delete an experiment we would need to delete the experiment record form the SQL db.  This will orphan all related jobs, tags, metrics, etc. and may undercut the core feature of reproducibility. For now the best resolution may be to extend support for restoring experiments using the mlflow tracking backend.

**Comment by keithmanville** [comment]
won't fix

**Comment by austinvhuang** [comment]
if this is the intent, it seems like incorrect UI/UX to let the user delete an experiment in the first place (especially as a harmless looking trash can) and be left with invisible experiment names that error out when they're chosen.

**Comment by jkglasbrenner** [comment]
Hi @austinvhuang, thank you for the feedback. For context, this discussion is related to the pre-alpha version of Dioptra (sometimes referred to as Dioptra v0). It doesn't apply to Dioptra v1, which has a different data model and is the current release on `main`.
