### ISSUE TITLE
Update examples to use formalized and expanded Dioptra Client

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#265]
Once the Dioptra Client has been fully migrated and expanded in the `dioptra` package, the examples need to be updated to use the client.

In addition to updating the code for the examples, the documentation needs to be updated as well. To use the packaged client, the `dioptra` package will need to be installed in the virtual environment set up for the examples.

## Depends On

- #210 
- #543  

## Definition of Done

- [ ] Update Documentation for examples - in particular update how the virtual environment is installed (dioptra package is now needed)
- [ ] Update examples to use the new API
- [ ] [examples/scripts/client.py](https://github.com/usnistgov/dioptra/blob/744cd46f585ece49e21ea22a88899ce1fd0eb4a8/examples/scripts/client.py) is deleted

**Comment by keithmanville** [comment]
stale
