### ISSUE TITLE
Add Shared Resource tables to Dioptra

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#289]
**Is your feature request related to a problem? Please describe.**

Add tables for Shared Resource to Dioptra.

Shared Resource table:
- id: int
- creator_id: int (User)
- resource_id: int (Resource)
- group_id: int (Group)
- created_on: Date
- readable: bool
- writeable: bool

**Definition of Done**
- Create Shared Resource table
- Unit and integration tests
- Migration script generated for alembic

**Additional context**

This is part of a series of issues that will follow these steps:
1. Add tables for "Group" and "Group Membership"
2. Add tables for "Resource" and "Shared Resource"
3. Extend existing schema  to link up with Resource metadata
4. Add  Oso policy and integrate w/ service layer
5. Add  `/resource` and `/sharedresource` REST API endpoints

**Comment by jkglasbrenner** [comment]
Superceded by database and full ORM redesign.
