### ISSUE TITLE
Create dioptra-worker command for launching a Dioptra worker without a container

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#296]
Make it possible to launch a worker instance without docker to support Dioptra developer workflows and experiment prototyping workflows.

## Basic requirements

The general ask is to replicate the current behavior of the `start_rq()` function in the [entrypoint-worker.m4](https://github.com/usnistgov/dioptra/blob/a76b919310267893a392bdb7f5b5e916909aba72/docker/shellscripts/entrypoint-worker.m4) script with a `dioptra-worker` command that is provided by the dioptra package.

A few things that will need to be done to accomplish this (this may not be exhaustive, but it should hit on the most important points):

- Launch the [RQ workers](https://python-rq.org/) using the `dioptra-worker` command and pass any configurations as appropriate. Currently the RQ workers are launched using [dioptra.rq.cli.rq](https://github.com/usnistgov/dioptra/blob/d9079d87d807fee80bd3ce1d30d5a6765d04bada/src/dioptra/rq/cli/rq.py), which just calls the [rq package's Click interface](https://github.com/rq/rq/blob/master/rq/cli/cli.py).
- **For legacy jobs:** Port the remainder of the [run-mlflow-job.m4 script](https://github.com/usnistgov/dioptra/blob/26ce1c85cb8c233e31bc72ee0f30e96db0c05b39/docker/shellscripts/run-mlflow-job.m4) into [rq/tasks/run_mlflow.py](https://github.com/usnistgov/dioptra/blob/26ce1c85cb8c233e31bc72ee0f30e96db0c05b39/src/dioptra/rq/tasks/run_mlflow.py).
    - By extension, the [run-mlflow-job.m4 script](https://github.com/usnistgov/dioptra/blob/26ce1c85cb8c233e31bc72ee0f30e96db0c05b39/docker/shellscripts/run-mlflow-job.m4) script will be able to be deleted.
    - Leverage/adapt [dioptra.rq.cli.mlflow](https://github.com/usnistgov/dioptra/blob/d9079d87d807fee80bd3ce1d30d5a6765d04bada/src/dioptra/rq/cli/mlflow.py) for invoking the legacy job task.
- Figure out if there is any additional functionality in the worker containers, for example [Dockerfile.tensorflow2-cpu](https://github.com/usnistgov/dioptra/blob/26ce1c85cb8c233e31bc72ee0f30e96db0c05b39/docker/Dockerfile.tensorflow2-cpu), that needs to be encapsulated in the `dioptra-worker` command
- Update the `start_rq()` function of [entrypoint-worker.m4](https://github.com/usnistgov/dioptra/blob/a76b919310267893a392bdb7f5b5e916909aba72/docker/shellscripts/entrypoint-worker.m4) to launch the worker using the `dioptra-worker` command.

When this is all done, it should be possible to start up a Dioptra worker without a container so long as it can see the Redis port.

**Comment by jkglasbrenner** [comment]
Closed by #403

**Comment by jkglasbrenner** [comment]
Closed by #403
