### ISSUE TITLE
Update the TensorFlow Feature Squeezing example to use the Task Engine

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#298]
Update the [TensorFlow Feature Squeezing example](https://github.com/usnistgov/dioptra/tree/dev/examples/tensorflow-mnist-feature-squeezing) to use the task engine.

## Definition of Done
- [x] The identified examples illustrate the use of the task execution engine

Examples to update:
- [x] tensorflow-mnist-feature-squeezing

**Comment by jkglasbrenner** [comment]
Closed by #308
