### ISSUE TITLE
Update the PyTorch MNIST Membership Inference example to use the Task Engine

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#302]
Update the [PyTorch MNIST Membership Inference example](https://github.com/usnistgov/dioptra/tree/dev/examples/pytorch-mnist-membership-inference) to use the task engine.

## Definition of Done
- [x] The identified examples illustrate the use of the task execution engine

Examples to update:
- [x] pytorch-mnist-membership-inference

**Comment by jkglasbrenner** [comment]
Closed by #320
