### ISSUE TITLE
Implement unit and integration tests for Experiments endpoint according to user stories

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#310]
Implement unit and integration tests for the Experiments endpoint according to user stories defined in #284 

Follow the integration test pattern from #281 

### Definition of Done
- [x] 100% coverage of Experiments endpoints

### Dependencies

depends on #284

**Comment by jkglasbrenner** [comment]
Closed by #322

The test coverage in controller.py still isn't 100%, but that is because there are `if` statements that are difficult to access. This won't be an issue after the endpoint refactors are finished, since that pushes all of the if/else logic into the service layer.
