### ISSUE TITLE
bug: Tests to not properly cleanup mlruns folder

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#337]
There is an issue that the mlruns folder is not properly cleaned up. This can cause subsequent runs of the tests to fail.

Modify the test so that when it runs, the mlruns folder gets placed in a temporary location that will be deleted.

Attempt to fix this with a new fixture that can be applied to each test without a lot of boilerplate.

**Comment by jkglasbrenner** [comment]
Closed by #354
