### ISSUE TITLE
Migrating the rest of the source code and documentation to the Dioptra namespace

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#38]
## Summary

A lot of the source code and documentation in this repository still makes references to "Securing AI" and to "MITRE". The MITRE references need to be removed[^1] and the "Securing AI" name needs to be replaced with "Dioptra". This migration was delayed because these will result in **breaking changes**.

[^1]: The references to MITRE is an artifact of this repository's development history that are no longer needed. MITRE transferred this code to NIST, and NIST open-sourced it to GitHub.

The following is a list of anticipated breaking changes:

- The `dioptra` package's import namespace will change from `mitre.securingai` to `dioptra`
- The task plugin namespaces will change from `securingai_builtins` and `securingai_custom` to `dioptra_builtins` and `dioptra_custom`
- The [taskPlugin REST API endpoints](https://github.com/usnistgov/dioptra/blob/e3bfeed8ec678ec192fb16bc4e3bc2ac7d8f1b6a/src/mitre/securingai/restapi/task_plugin/controller.py) will use `dioptra_builtins` and `dioptra_custom` instead of `securingai_builtins` and `securingai_custom`
- The name of the non-root user in the containers will change from `mitre` to `dioptra`.
- The virtual environment names in the containers will change from `mitre-securing-ai` to `dioptra`
- The prefixes of environment variables used in the containers and the `dioptra` Python package will change from `AI_` to `DIOPTRA_`

**Comment by jkglasbrenner** [comment]
Below is the current build of documentation after refactoring.

[2022-04-12 - Dioptra documentation - New Build.zip](https://github.com/usnistgov/dioptra/files/8484521/2022-04-12.-.Dioptra.documentation.-.New.Build.zip)

**Comment by hhuangMITRE** [comment]
I've confirmed that the backdoor poisoning and adversarial patch demos ran fine on the refactored branch, thanks!

**Comment by jkglasbrenner** [comment]
The refactor is working as expected in all existing unit and integration tests and for most of the examples. The examples that experienced breakage, such as the pixel threshold examples, are due to a change in the ART package's API and not the refactor itself. The fix for those will be handled using a different pull request. 

Since we haven't found anything obvious that was broken by the refactor, I'm going to go ahead and merge this to dev. Thanks everyone!
