### ISSUE TITLE
Required Fields in V1 Schemas not documented

### ISSUE THREAD

**Issue by alexb1200** [usnistgov/dioptra#415]
In the new Queue schema, name is a required field. https://github.com/usnistgov/dioptra/blob/7e40d156beba6071423551a4a8290dc12dccb626/src/dioptra/restapi/v1/queues/schema.py#L46

Should it be marked with `required=True` in the schema? So far we haven't done this for any of the schemas.

**Comment by keithmanville** [comment]
Will address later. Avoiding over specification for now.
