### ISSUE TITLE
[BUG] register_task_plugins.py should ignore hidden files/folders

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#421]
Currently the register_task_plugins.py script uploads every folder in the task-plugins directory. This isn't an issue for new clones of the repository, but when using jupyter notebook to edit the task plugins, it can cause the generation of an .ipynb_checkpoints folder which the script will then try to upload (and fail because of). 

Proposed fix: Ignore folders and files which start with the `.` character when choosing which files/folders to upload.

**Comment by keithmanville** [comment]
stale
