### ISSUE TITLE
Generating the Task Engine YAML files

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#504]
We need to create a function that constructs the [task engine YAML files](https://pages.nist.gov/dioptra/user-guide/task_engine_doc.html) that will be executed by the worker containers. This function will be executed within the service layer, so it will need to request the information from the database using the ORM and construct the YAML document. The information we need is:

1. **Entry Point:** The latest snapshot for the entry point will give the **task graph** ("graph" section of YAML document). The ORM object has relationships that link to the list of **entry point parameters** ("parameters" section of YAML document) and plugin and plugin file snapshots.
2. **Plugin Tasks:** The Plugin File snapshots retrieved from the EntryPoint object link to the **plugin tasks**. The information in the Plugin + PluginFile + PluginTask ORM objects is needed to build the "tasks" section of the YAML document.
3. **Plugin Parameter Types:** Each PluginTask ORM object has the input_parameters and output_parameters attributes. Each of these attributes is a list containing PluginTaskInputParameter and PluginTaskOutputParameter objects, respectively. Each out of these input/output parameter objects links to a PluginTaskParameterType object. The full set of these input/output parameter type objects is needed to build the "types" section of the YAML document.

Once this information has been fetched from the database, it needs to be structured according to the [task engine spec](https://pages.nist.gov/dioptra/user-guide/task_engine_doc.html#structure-description) and exported to YAML. This PyYAML library can be used for the YAML export, since its already declared as a Dioptra dependency.

**Note:** This function will be executed in the Entry Point service layer, but most of the functionality can be written outside of the REST API and brought in once its working. The easiest way to test without running the Flask app is to create a SQLAlchemy Session, see https://docs.sqlalchemy.org/en/20/orm/session_basics.html#querying.

**Comment by keithmanville** [comment]
closed by #516
