### ISSUE TITLE
[BUG] Inconsistent display of Groups in the front end

### ISSUE THREAD

**Issue by etrapnell-nist** [usnistgov/dioptra#533]
**Describe the bug**
When first navigating to the Groups endpoint, the public group is listed twice. Selecting the radio button for one selects/deselects both rows, and the table footer text displays "1 record selected." Upon refreshing the page, both rows disappear and ""No data available" is displayed. After navigating away and coming back, the public group is listed twice again.

**Expected behavior**
The public group should be listed a single time and persist through a page refresh.

**Screenshots**
<img width="1140" alt="groups_double" src="https://github.com/user-attachments/assets/6352ea5e-ef2a-498a-ada4-c5f3c1787541">

<img width="1147" alt="groups_none" src="https://github.com/user-attachments/assets/915a002a-5629-4f5b-b646-e860fa47cbb7">

**Desktop (please complete the following information):**
 - OS: macOS 14.5

 - Browser: Firefox version 127.0.2

**Comment by henrychoy** [comment]
Not sure why this is happening, but I updated it so that it looks at the user's id rather than username when finding the groups.  I also hid the edit and delete buttons since that functionality is not yet available for groups.

Can you try the branch `models-and-artifacts-frontend` and let me know if it's still happening?

**Comment by etrapnell-nist** [comment]
I tried this on the branch models-and-artifacts-frontend and the double group display issue isn't present. However, the group still disappears after refreshing the page until I navigate away and come back.

**Comment by jkglasbrenner** [comment]
Closed by #532
