### ISSUE TITLE
[BUG] Web UI- Plugin-Params register button not functioning and has incorrect tooltip

### ISSUE THREAD

**Issue by mtrapnell-nist** [usnistgov/dioptra#534]
**Describe the bug**
When mousing over the + button on the Plugin-Params tab, the tooltip is "Register a new Plugin" and does nothing when clicked (no errors are displayed either).

**To Reproduce**
1. Login to a user account
2. Navigate to Plugin-Params tab
3. Hover over the + button to see the incorrect tooltip
4. Click the + button at the bottom right of the page
5. No page is opened to allow the user to create a new plugin parameter type

**Expected behavior**
The button should display a tooltip for creating a plugin parameter type instead of a plugin and open a page to create a new plugin parameter type.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser Firefox
 - Version 128.0

**Comment by henrychoy** [comment]
This has been fixed in the `models-and-artifacts-frontend` branch.  The tooltip has been updated and clicking the button should bring up a dialog box.  Let me know if it works for you on that branch.

**Comment by mtrapnell-nist** [comment]
I tried it out and it all seems to be fixed now on that branch.
