### ISSUE TITLE
[BUG] Web UI menu bar - resizing browser window causes elements to disappear

### ISSUE THREAD

**Issue by mtrapnell-nist** [usnistgov/dioptra#538]
**Describe the bug**
When resizing the browser window, the logged in user button and group selection drop down can completely disappear from the menu on the top right corner. No window scroll bar appears at the bottom to allow access to those buttons. If the user's window is too small when first navigating to the Dioptra UI, the user may not be able to login, since this also happens for the "Sign In" button. 

There is a certain point when shrinking the window size causes a menu drop down button to be displayed, but other buttons will disappear if the window size isn't small enough to trigger this switch to compact mode.

**Expected behavior**
As soon as the browser window is too small to display the full menu bar, it should switch to the compact UI.

**Screenshots**
An arrow appears inside the user login element, but will disappear if the window is shrunk more:
![menu_bar user login button cut off](https://github.com/user-attachments/assets/93be75f1-7b8b-49de-a2ed-ca607c0492b0)

Sign in button partially hidden:
![menu_bar- sign in button cut off](https://github.com/user-attachments/assets/3650540a-c6c0-441b-8010-43deb2e6bee0)

Shrinking the browser window more causes the Sign In button to disappear:
![menu_bar- sign in button not visible](https://github.com/user-attachments/assets/bc8e9374-e82e-43a8-949a-373806c4ad22)

The Artifacts menu element is not visible, and no scroll bar appears in the browser window:
![menu_bar- some elements are hidden](https://github.com/user-attachments/assets/2673efd4-c3c1-44c7-9851-b5b978553c00)
  
  

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser: Firefox
 - Version: 128.0

**Comment by jkglasbrenner** [comment]
Closed by #532
