### ISSUE TITLE
Implement new pages for models and artifacts in the UI

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#541]
Add new top level pages for browsing models and artifacts in the user interface. These pages should follow the common table interface used by other resources.

Add new UI elements to the Job display page to show artifacts associated with a Job.

### Definition of Done
- [x] The user can browse and search a table of models and artifacts in their respective pages
- [x] The user can see the artifacts created by a job when examining the details of a job.

**Comment by jkglasbrenner** [comment]
Closed by #532
