### ISSUE TITLE
Implement a new Python client that covers v1 of the REST API

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#543]
Implement a Python client for the new REST API.

The client should manage sessions internally. The implementation should use composition to handle each of the endpoints in the REST API. It should include error handling and raise an exception when a status code other than 200 is received. The client should return only JSON responses as Python dictionaries to the user.

Here is an example of what the base client class should look like using composition:
```python
class DioptraClient(object):
    def __init__(self, dioptra_api_url):
        self._experiments = ExperimentEndpoint(...)
        self._jobs = JobEndpoint
        self._queues = queue
        # Set other endpoint objects in the same manner

    @property
    def experiments(self):
        return self._experiments

    @property
    def jobs(self):
        return self._jobs

    @property
    def queues(self):
        return self._queues
```

And one of the Endpoint classes
```python
class QueueClient(object):
    def get_all(self) -> list[dict[str, Any]]:
        # Body of function follows

    def create(
        self,
        name: str,
        group: int,
    ) -> dict[str, Any]:
    # Body of function follows

# Classes like ExperimentClient, JobClient follow
```

See #211 for additional documentation on the client re-design.

See #608 for additional tests on subendpoints under experiments and entrypoints.

**Comment by jkglasbrenner** [comment]
Closed by #689
