### ISSUE TITLE
Improve color contrast for experiment links in dark mode

### ISSUE THREAD

**Issue by etrapnell-nist** [usnistgov/dioptra#548]
**Describe the bug**
On the experiments endpoint, experiment links are difficult to read for both visited and not visited experiments.

**Expected behavior**
Experiment names should be easy to read with colors that provide sufficient contrast.

**Screenshots**
<img width="987" alt="experiments" src="https://github.com/user-attachments/assets/f7be63d6-7601-4888-b8c4-cce32066c983">

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser Firefox
 - Version 128.0

**Comment by henrychoy** [comment]
@etrapnell-nist This has been fixed in this PR: https://github.com/usnistgov/dioptra/pull/571

**Comment by etrapnell-nist** [comment]
Looks great now, thanks.

**Comment by keithmanville** [comment]
resolved by #571
