### ISSUE TITLE
Endpoint tables become difficult to read with large amounts of text

### ISSUE THREAD

**Issue by etrapnell-nist** [usnistgov/dioptra#553]
**Description**
Endpoint tables become difficult to read if text-containing elements such as name, description, or tags are long.

**Suggested behavior**
Truncating long text fields and allowing the option to display the remainder would make them easier to read.

**Comment by henrychoy** [comment]
@etrapnell-nist, this PR should address this issue.  https://github.com/usnistgov/dioptra/pull/555
