### ISSUE TITLE
Improve REST API test coverage

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#593]
Some portions of the v1 REST API are not covered by tests.

Identify endpoints that are not tested or could benefit from additional testing. Write a user story to help design new tests and implement them in the appropriate test suite.

These endpoints have already been identified as having a testing gap:
- /api/v1/entrypoints/{id}/queues
- /api/v1/entrypoints/{id}/queues/{id}
- /api/v1/entrypoints/{id}/plugins
- /api/v1/entrypoints/{id}/plugins/{id}
- /api/v1/experiments/{id}/entrypoints
- /api/v1/experiments/{id}/entrypoints/{id}

### Definition of done:
- [x] New tests are implemented to improve coverage
- [x] All new and existing tests pass

**Comment by jkglasbrenner** [comment]
Closed by #689
