### ISSUE TITLE
[BUG] Init Frontend: error during build: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by Cachet23** [usnistgov/dioptra#661]
**Describe the bug**
./init-deployment.sh --branch $DIOPTRA_BRANCH skript fails with docker images built from main as well as from dev.

**To Reproduce**
Steps to reproduce the behavior: [these are exactly my steps]
1. clean up docker images to avoid building images from cache
2. rm -rf dioptra -> to start clean
3. git clone dioptra repo via https or ssh
5. [git checkout -b dev origin/dev] tried both
6. execute the make command as shown in the documentaion (https://pages.nist.gov/dioptra/getting-started/building-the-containers.html)
7. I created a Directory 'dioptra-deployments' outside the dioptra repo -> "home/user/dioptra-data"
8. inside that directory i created the venv -> sourced it -> used the command to install cruft and jinja as shown in the documentation (with additional --no-cache-dir) 
9. export the DIOPTRA_BRANCH=dev
10. run cruft command -> fill out the template exactly like this:

deployment_name [Dioptra deployment]: Dioptra deployment
container_registry []:
container_tag [dev]: dev
docker_compose_path [docker compose]: docker compose
systemd_required_mounts []:
nginx_server_name [dioptra.example.org]: _
Select nginx_expose_ports_on_localhost_only:
1 - True
2 - False
Choose from 1, 2 [1]: 1
postgres_container_tag [15]: 15
pgadmin_default_email [dioptra@example.com]: dioptra@example.com
num_tensorflow_cpu_workers [1]: 1
num_tensorflow_gpu_workers [0]: 0
num_pytorch_cpu_workers [1]: 1
num_pytorch_gpu_workers [0]: 0
datasets_directory []: home/user/dioptra-data

11. cd into dioptra-deployment
12. run init-deployment skript
==> it fails

**Screenshots**
![image](https://github.com/user-attachments/assets/9f4ac942-f52c-4b12-9557-d91ee8bfe593)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - WSL: Ubuntu 22.04
 - Docker Compose version v2.29.2-desktop.2
 -  Docker-Engine: Version:          27.2.0

**Comment by Cachet23** [comment]
fixed by adding a patch function in the init-frontend.sh skript that replaces a relative path with an absolute path to the missing file. I patch right before  compile_vue_js_frontend() and after prepare_build_dir().

sorry for making an issue out of this. Feel free to remove it

**Comment by hbooth** [comment]
Thank you for letting us know about the issue. We will try figure out the best way to resolve this.

**Comment by jkglasbrenner** [comment]
Closed by #663
