### ISSUE TITLE
Pin npm dependencies

### ISSUE THREAD

**Issue by keithmanville** [usnistgov/dioptra#662]
Pin the npm dependencies by generating a lock file to prevent frontend builds from breaking unexpectedly.

**Comment by jkglasbrenner** [comment]
@hbooth @henrychoy I looked into this and we do have `package-lock.json` in the dev branch now, which is supposed to take care of this. The problem I think is in the `init-deployment.sh` file, which calls a script called `init-frontend.sh`:

- The `package-lock.json` file wasn't being copied into the build context in `init-frontend.sh`, so it was being completely ignored.
- The `init-frontend.sh` script was using `npm install`, which will update the lockfile under some circumstances. The recommended command for reproducible installs with a lockfile is `npm ci`.

I pushed Pull Request #663 with these changes. We'll need someone to validate that this works as a stopgap for the problem discussed in #661.

**Comment by Cachet23** [comment]
I rebuilt the images -> ran the cruft command and filled out the template as shown in #661 -> config folders and skripts got generated -> ran init-deployment.sh skript and it perfectly built the frontend with npm ci!

So from my side of things everything builds fine now :)
thank you for fixing this!

**Comment by jkglasbrenner** [comment]
Closed by #663
