### ISSUE TITLE
REST API - Cannot retrieve an experiment name if a capital letter is used

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#71]
## Description of bug

The bug happens when calling the GET method on the `experiment/name/<string:experimentName>` endpoint and `<string:experimentName>` contains a capital letter.

https://github.com/usnistgov/dioptra/blob/e68a0f40d6600582e9e3538faf0ceca86192f18f/src/dioptra/restapi/experiment/controller.py#L175-L189

`experimentName` is passed to `ExperimentService.get_by_name`, which does a database lookup and fails.

https://github.com/usnistgov/dioptra/blob/e68a0f40d6600582e9e3538faf0ceca86192f18f/src/dioptra/restapi/experiment/service.py#L150-L156

The lookup can fail because experiment names are intended to be case insensitive, and upon registration they are slugified (to keep them standardized):

https://github.com/usnistgov/dioptra/blob/e68a0f40d6600582e9e3538faf0ceca86192f18f/src/dioptra/restapi/experiment/schema.py#L98-L107

## How to fix

All methods in `ExperimentService` should slugify `experiment_name` before querying the database.

**Comment by pauldavidrowe** [comment]
See also #161

**Comment by jkglasbrenner** [comment]
Closed by #175
