### ISSUE TITLE
Documentation topic areas

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#82]
## Definition of Done

- [ ] Have a list of topic areas
- [ ] Have an Issue card covering each topic area for creation, revision, expansion, or deletion

**Comment by pauldavidrowe** [comment]
- Need overview of installation options/types
  - Local
  - On-prem
  - Distributed

- Update docs once templated deployment script is complete

- Fill in Setup Tips for Newcomers

- User Guide
  - Add orientation page with basic assumptions
    * "We assume you have access to a deployment..."
    * Add distinction between "browsing/running" existing content and "creating" new content
  - Integrate documentation for declarative task engine
    * Consider reorganizing to start with guide for using existing material, then advancing to adding new material.
    * Consider separating guide into "running" vs "creating" experiments
  - Custom Task Plugins
    * Update to reflect 3-way distinction: built-in/custom/local
  - Creating Entry Points
    * Improve diagram at top

- Tutorials & Examples
  - Add orientation material in a "landing page"
    * Describe purpose of this sequence: demonstrate possible Dioptra uses
    * Unify basic setup instructions at top-level to avoid duplication
    * Include high-level (2-3 sentence) summary of each example?
  - Update all examples to assume basic setup has occurred
  - Add at least one example that uses declarative format

- Developer's Guide
  - Update Getting Involved / Contributing
    * Sync with contributor's guide
  - Write Programming Style Guide
  - Write REST API Developer's Guide

- Plan out UI documentation
  - Update existing docs with UI info or have its own section?
