### ISSUE TITLE
Updating the examples to leverage the new deployment process with templates

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#84]
## Overview

The current examples do not use a common method for deploying Dioptra. Once the implementation in #83 is completed, the examples need to be standardized to all refer to and use this deployment process.

## Definition of Done

- [ ] All existing examples are refactored to be compatible with the new deployment process.
- [ ] Examples documentation is updated to describe the new process for running the demos

**Comment by hbooth** [comment]
Duplicate for #152
