### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#88]
Meet to discuss design and implementation details, this issue and #89 should both be closed in favor of the issues generated by this discussion.

## Implementation Goals

We do not want to implement any of the solutions from scratch, leverage existing libraries!

## Libraries

- [Authlib (Python)](https://docs.authlib.org/en/latest/), there is a [Flask OAuth 2.0 Server example](https://docs.authlib.org/en/latest/flask/2/index.html), is it good enough or need additional pieces?

## Definition of Done

- [ ] Modular solution that can support at least 3 modes of operation, file-based authentication, database authentication, OAuth2/SAML/SSO-based authentication
- [ ] Come to a decision of whether the user identities live in the authentication service itself, or are also stored/managed as part of the application

**Comment by hbooth** [comment]
see also #89

**Comment by hbooth** [comment]
Replaced by more granular issues to get to the same point:
#221 #222
