### ISSUE TITLE
Authorization and Access Control

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#89]
Meet to discuss design and implementation details, this issue and #88 should both be closed in favor of the issues generated by this discussion.

## Overview

![gbac-entity-relationship-diagram](https://user-images.githubusercontent.com/8547754/195158324-d3aa778e-7b98-46dc-9e4e-d55169260a5b.png)

## Libraries

- [Oso](https://www.osohq.com/docs)

## Definition of Done

- [ ] All existing REST endpoints are placed under group-based access control

**Comment by hbooth** [comment]
see also #88

**Comment by hbooth** [comment]
Closed in favor of more granular issues
#223 #225 and any follow-ons to those
