### ISSUE TITLE
Task Execution Engine

### ISSUE THREAD

**Issue by jkglasbrenner** [usnistgov/dioptra#90]
## Notes

Regarding the validation mechanism, this has a few aspects:

- Structural/schematic correctness, i.e. the types and input names conform to the task plugins that are registered in Dioptra
- Flow validation, the expected type of downstream inputs matches with the provided upstream outputs
- Graph validation, is it a directed acyclic graph (DAG), or does it have erroneous cycles?

## Definition of Done

- [x] Declarative model for defining and executing experiments leveraging the task plugins
- [x] Engine provides a syntactic and schematic validation mechanism for declarative files
- [x] Documentation on how to create experiments that run using the task engine
- [x] Task engine functionality has unit tests
- [ ] Task execution engine code and documentation are merged to dev branch
~~- [ ] Key examples are extended to demonstrate how to use the task engine~~

**Comment by pauldavidrowe** [comment]
This should be closed when #101 is closed.

**Comment by pauldavidrowe** [comment]
Closing because it will be pushed with #101
