### ISSUE TITLE
Unit Testing - SDK Utilities

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#97]
This is the list of functions in the `src/dioptra/sdk` folder that will need unit tests.

**Generics:**
- [ ] [`estimator_predict` in src/dioptra/sdk/generics/_estimator_predict.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/generics/_estimator_predict.py)
- [ ] [`fit_estimator` in src/dioptra/sdk/generics/_fit_estimator.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/generics/_fit_estimator.py)

**Object Detectors**
(Note: Some of the classes in this folder are currently unimplemented and are not included below.)
- [ ] [`ARTYOLOV1ObjectDetector` in object_detection/architectures/yolov1.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/architectures/yolov1.py)
- [ ] [`YOLOV1ObjectDetector` in object_detection/architectures/yolov1.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/architectures/yolov1.py)
- [ ] [`ImgAugObjectDetectionAugmentations` in object_detection/augmentations/imgaug_backend.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/augmentations/imgaug_backend.py)
- [ ] [`PassthroughObjectDetectionAugmentations` in object_detection/augmentations/passthrough.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/augmentations/passthrough.py)
- [ ] [`TensorflowBoundingBoxesIOU` in object_detection/bounding_boxes/iou/tensorflow_backend.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/bounding_boxes/iou/tensorflow_backend.py)
- [ ] [`TensorflowBoundingBoxesBatchedGridIOU` in object_detection/bounding_boxes/iou/tensorflow_backend.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/bounding_boxes/iou/tensorflow_backend.py)
- [ ] [`TensorflowObjectDetectionData` in object_detection/data/tensorflow_backend.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/data/tensorflow_backend.py)
- [ ] [`NumpyAnnotationEncoding` in object_detection/data/annotations/encodings.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/data/annotations/encodings.py)
- [ ] [`PascalVOCAnnotationData` in object_detection/data/annotations/pascal_voc.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/data/annotations/pascal_voc.py)
- [ ] [`TensorflowImageData` in object_detection/data/images/tensorflow_backend.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/data/images/tensorflow_backend.py)
- [ ] [`YOLOV1LocalizationLoss` in object_detection/losses/yolov1/localization.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/losses/yolov1/localization.py)
- [ ] [`YOLOV1Loss` in object_detection/losses/yolov1/yolov1.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/losses/yolov1/yolov1.py)
- [ ] [`YOLOV1ClassificationLoss` in object_detection/losses/yolov1/classification.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/object_detection/losses/yolov1/classification.py)

**Utilities:**
- [ ] [`plugin_dirs` in src/dioptra/sdk/utilities/contexts/_plugin_dirs.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/utilities/contexts/_plugin_dirs.py)
- [ ] [`redirect_print` in src/dioptra/sdk/utilities/contexts/_redirect_print.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/utilities/contexts/_redirect_print.py)
- [ ] [`require_package` in src/dioptra/sdk/utilities/decorators/_require_package.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/sdk/utilities/decorators/_require_package.py)

**Comment by keithmanville** [comment]
Replaced by #292
