### ISSUE TITLE
Unit Testing - Pyplugs and Generics

### ISSUE THREAD

**Issue by jtsextonMITRE** [usnistgov/dioptra#99]
This is the list of functions in the `src/dioptra/pyplugs` and `/src/dioptra/generics_plugins` folders which will likely need unit tests, as they are exposed functions. Note that `/src/dioptra/mlflow_plugins` has been specifically excluded, because integration tests will serve that directory better than unit tests will.

**Pyplugs:**

- [ ] [`ImportError` in src/dioptra/pyplugs/_plugins.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/pyplugs/_plugins.py#L80)
- [ ] [`ImportError` in src/dioptra/pyplugs/_plugins.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/pyplugs/_plugins.py#L86)
- [ ] [`ImportError` in src/dioptra/pyplugs/_plugins.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/pyplugs/_plugins.py#L95)

**Generics Plugins:**
- [ ] [`keras_model_predict_proba` in src/dioptra/generics_plugins/estimator_predict/tf_keras_model.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/generics_plugins/estimator_predict/tf_keras_model.py)
- [ ] [`keras_model_predict_label` in src/dioptra/generics_plugins/estimator_predict/tf_keras_model.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/generics_plugins/estimator_predict/tf_keras_model.py)
- [ ] [`fit_keras_model` in src/dioptra/generics_plugins/fit_estimator/tf_keras_model.py](https://github.com/usnistgov/dioptra/blob/main/src/dioptra/generics_plugins/fit_estimator/tf_keras_model.py)

**Comment by keithmanville** [comment]
Won't fix
